# Golang version - Docker Hub (hub.docker.com)
FROM golang:alpine3.12

# Enviornment variables
ENV APP_NAME app
ENV PORT 8080

# Open system port
EXPOSE ${PORT}

# Working directory
WORKDIR /go/src/${APP_NAME}

COPY . /go/src/${APP_NAME}

# Install dependecies from mod file
RUN go mod download

# Hot reloading for development!
RUN go get github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon --build="go build -o app" --command=./app
